Add support for multi-kernel builds. Common part for multi-kernel build should be configured with -DUSER_PART_ONLY=on, kernel part - with -DKERNEL_PART_ONLY=on. After 'make install' for kernel part 'depmod' should be executed manually.
Some tests are disabled in multi-kernel builds, because there existence depends on the kernel.

List of payloads for configuration files now is collected using cmake GLOBAL properties.
Configuration files themselves are written using file_update() function in /sources/tools/control/CMakeLists.txt.

diff --git a/sources/tests/core/payload_api/basics/test_change_target.sh.in b/sources/tests/core/payload_api/basics/test_change_target.sh.in
--- a/sources/tests/core/payload_api/basics/test_change_target.sh.in
+++ b/sources/tests/core/payload_api/basics/test_change_target.sh.in
@@ -7,20 +7,16 @@
 #
 # The target modules should be: <targetN_dir>/test_<targetN_dir>.ko
 ########################################################################
-
-# Just in case the tools like lsmod are not in their usual location.
-export PATH=$PATH:/sbin:/bin:/usr/bin
-
 ########################################################################
 # A function to check prerequisites: whether the necessary files exist,
 # etc.
 ########################################################################
 checkPrereqs()
 {
-	if test ! -f "${KEDR_MODULE}"; then
-		printf "KEDR core module is missing: ${KEDR_MODULE}\n"
-		exit 1
-	fi
+	#if test ! -f "${KEDR_MODULE}"; then
+	#	printf "KEDR core module is missing: ${KEDR_MODULE}\n"
+	#	exit 1
+	#fi
 	
 	if test ! -f "${TARGET_MODULE1}"; then
 		printf "Target module is missing: ${TARGET_MODULE1}\n"
@@ -45,24 +41,24 @@ cleanupAll()
 {
 	cd "${WORK_DIR}"
 	
-	lsmod | grep "${TARGET_NAME1_ACTUAL}" > /dev/null 2>&1
+	@LSMOD@ | grep "${TARGET_NAME1_ACTUAL}" > /dev/null 2>&1
 	if test $? -eq 0; then
-		rmmod "${TARGET_NAME1_ACTUAL}"
+		@RMMOD@ "${TARGET_NAME1_ACTUAL}"
 	fi
 	
-	lsmod | grep "${TARGET_NAME2_ACTUAL}" > /dev/null 2>&1
+	@LSMOD@ | grep "${TARGET_NAME2_ACTUAL}" > /dev/null 2>&1
 	if test $? -eq 0; then
-		rmmod "${TARGET_NAME2_ACTUAL}"
+		@RMMOD@ "${TARGET_NAME2_ACTUAL}"
 	fi
 	
-	lsmod | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
+	@LSMOD@ | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
 	if test $? -eq 0; then
-		rmmod "${PAYLOAD_NAME}"
+		@RMMOD@ "${PAYLOAD_NAME}"
 	fi
 	
-	lsmod | grep "@CORE_NAME@" > /dev/null 2>&1
+	@LSMOD@ | grep "@KEDR_CORE_NAME@" > /dev/null 2>&1
 	if test $? -eq 0; then
-		rmmod "@CORE_NAME@"
+		@RMMOD@ "@KEDR_CORE_NAME@"
 	fi
 }
 
@@ -105,9 +101,9 @@ checkOutputStrings()
 ########################################################################
 doTest()
 {
-	insmod "${KEDR_MODULE}" target_name="${TARGET_NAME1}" || exit 1
+	@KEDR_CORE_LOAD_COMMAND@ target_name="${TARGET_NAME1}" || exit 1
 
-	insmod "${PAYLOAD_MODULE}" \
+	@INSMOD@ "${PAYLOAD_MODULE}" \
 		set_load_fn=1 \
 		set_unload_fn=1
 	if test $? -ne 0; then
@@ -133,7 +129,7 @@ doTest()
 		exit 1
 	fi
 
-	insmod "${TARGET_MODULE1}"
+	@INSMOD@ "${TARGET_MODULE1}"
 	if test $? -ne 0; then
 		printf "Failed to load the target module: ${TARGET_NAME1}\n"
 		cleanupAll
@@ -142,7 +138,7 @@ doTest()
 
 	checkOutputStrings "${EXPECTED_LOAD_STRING}" "<none>"
 
-	rmmod "${TARGET_NAME1_ACTUAL}"
+	@RMMOD@ "${TARGET_NAME1_ACTUAL}"
 	if test $? -ne 0; then
 		printf "Failed to unload the target module: ${TARGET_NAME1}\n"
 		cleanupAll
@@ -152,7 +148,7 @@ doTest()
 	checkOutputStrings "${EXPECTED_LOAD_STRING}" "${EXPECTED_UNLOAD_STRING}"
 	
 	# Instruct KEDR to look for another target module
-	echo "${TARGET_NAME2}" > "/sys/module/@CORE_NAME@/parameters/target_name"
+	echo "${TARGET_NAME2}" > "/sys/module/@KEDR_CORE_NAME@/parameters/target_name"
     if test $? -ne 0; then
         printf "Failed to set target name.\n"
         cleanupAll
@@ -161,7 +157,7 @@ doTest()
 	
 	EXPECTED_LOAD_STRING="${TARGET_NAME2_ACTUAL}"
 	
-	insmod "${TARGET_MODULE2}"
+	@INSMOD@ "${TARGET_MODULE2}"
 	if test $? -ne 0; then
 		printf "Failed to load the target module: ${TARGET_NAME2}\n"
 		cleanupAll
@@ -172,7 +168,7 @@ doTest()
 	
 	EXPECTED_UNLOAD_STRING="${TARGET_NAME2_ACTUAL}"
 	
-	rmmod "${TARGET_NAME2_ACTUAL}"
+	@RMMOD@ "${TARGET_NAME2_ACTUAL}"
 	if test $? -ne 0; then
 		printf "Failed to unload the target module: ${TARGET_NAME2}\n"
 		cleanupAll
@@ -183,7 +179,7 @@ doTest()
 	
 	# Clear the target specification. KEDR should no longer watch for any
 	# target to load.
-	echo "none" > "/sys/module/@CORE_NAME@/parameters/target_name"
+	echo "none" > "/sys/module/@KEDR_CORE_NAME@/parameters/target_name"
     if test $? -ne 0; then
         printf "Failed to clear target specification.\n"
         cleanupAll
@@ -192,14 +188,14 @@ doTest()
     
     # Load and unload the first target again and check that the payload 
     # has not been notified.
-    insmod "${TARGET_MODULE1}" 
+    @INSMOD@ "${TARGET_MODULE1}" 
 	if test $? -ne 0; then
 		printf "Failed to load the target module: ${TARGET_NAME1}\n"
 		cleanupAll
 		exit 1
 	fi
 	
-	rmmod "${TARGET_NAME1_ACTUAL}"
+	@RMMOD@ "${TARGET_NAME1_ACTUAL}"
 	if test $? -ne 0; then
 		printf "Failed to unload the target module: ${TARGET_NAME1}\n"
 		cleanupAll
@@ -219,23 +215,23 @@ if test $# -ne 2; then
 	exit 1
 fi
 
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
+
 TARGET_DIR1=$1
 TARGET_DIR2=$2
 
-KEDR_MODULE="@KEDR_INSTALL_PREFIX_KMODULE@/@CORE_NAME@.ko"
-
 TARGET_NAME1="test_${TARGET_DIR1}"
 TARGET_NAME1_ACTUAL=$(echo "${TARGET_NAME1}" | tr '-' '_')
-TARGET_MODULE1="${TARGET_DIR1}/${TARGET_NAME1}.ko"
+TARGET_MODULE1="${TARGET_DIR1}/${KERNEL}/${TARGET_NAME1}.ko"
 
 TARGET_NAME2="test_${TARGET_DIR2}"
 TARGET_NAME2_ACTUAL=$(echo "${TARGET_NAME2}" | tr '-' '_')
-TARGET_MODULE2="${TARGET_DIR2}/${TARGET_NAME2}.ko"
+TARGET_MODULE2="${TARGET_DIR2}/${KERNEL}/${TARGET_NAME2}.ko"
 
 printf "Target modules: ${TARGET_MODULE1}, ${TARGET_MODULE2}\n"
 
 PAYLOAD_NAME="test_basics_payload"
-PAYLOAD_MODULE="payload/${PAYLOAD_NAME}.ko"
+PAYLOAD_MODULE="payload/${KERNEL}/${PAYLOAD_NAME}.ko"
 
 ################################
 checkPrereqs
diff --git a/sources/tests/core/payload_api/basics/test_set_target.sh.in b/sources/tests/core/payload_api/basics/test_set_target.sh.in
--- a/sources/tests/core/payload_api/basics/test_set_target.sh.in
+++ b/sources/tests/core/payload_api/basics/test_set_target.sh.in
@@ -9,20 +9,16 @@
 #
 # Target module should be <target_dir>/test_<target_dir>.ko
 ########################################################################
-
-# Just in case the tools like lsmod are not in their usual location.
-export PATH=$PATH:/sbin:/bin:/usr/bin
-
 ########################################################################
 # A function to check prerequisites: whether the necessary files exist,
 # etc.
 ########################################################################
 checkPrereqs()
 {
-    if test ! -f "${KEDR_MODULE}"; then
-        printf "KEDR core module is missing: ${KEDR_MODULE}\n"
-        exit 1
-    fi
+    #if test ! -f "${KEDR_MODULE}"; then
+    #    printf "KEDR core module is missing: ${KEDR_MODULE}\n"
+    #    exit 1
+    #fi
     
     if test ! -f "${TARGET_MODULE}"; then
         printf "Target module is missing: ${TARGET_MODULE}\n"
@@ -42,19 +38,19 @@ cleanupAll()
 {
     cd "${WORK_DIR}"
     
-    lsmod | grep "${TARGET_NAME_ACTUAL}" > /dev/null 2>&1
+    @LSMOD@ | grep "${TARGET_NAME_ACTUAL}" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "${TARGET_NAME_ACTUAL}"
+        @RMMOD@ "${TARGET_NAME_ACTUAL}"
     fi
     
-    lsmod | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
+    @LSMOD@ | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "${PAYLOAD_NAME}"
+        @RMMOD@ "${PAYLOAD_NAME}"
     fi
     
-    lsmod | grep "@CORE_NAME@" > /dev/null 2>&1
+    @LSMOD@ | grep "@KEDR_CORE_NAME@" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "@CORE_NAME@"
+        @RMMOD@ "@KEDR_CORE_NAME@"
     fi
 }
 
@@ -97,9 +93,9 @@ checkOutputStrings()
 ########################################################################
 doTest()
 {
-    insmod "${KEDR_MODULE}" || exit 1
+    @KEDR_CORE_LOAD_COMMAND@ || exit 1
 
-    insmod "${PAYLOAD_MODULE}" \
+    @INSMOD@ "${PAYLOAD_MODULE}" \
         set_load_fn=1 \
         set_unload_fn=1
     if test $? -ne 0; then
@@ -126,14 +122,14 @@ doTest()
     fi
     
     # Set the target name now.
-    echo "${TARGET_NAME}" > "/sys/module/@CORE_NAME@/parameters/target_name"
+    echo "${TARGET_NAME}" > "/sys/module/@KEDR_CORE_NAME@/parameters/target_name"
     if test $? -ne 0; then
         printf "Failed to set target name.\n"
         cleanupAll
         exit 1
     fi
 
-    insmod "${TARGET_MODULE}"
+    @INSMOD@ "${TARGET_MODULE}"
     if test $? -ne 0; then
         printf "Initialization of the target module failed unexpectedly.\n"
         cleanupAll
@@ -142,7 +138,7 @@ doTest()
 
     checkOutputStrings "${EXPECTED_LOAD_STRING}" "<none>"
 
-    rmmod "${TARGET_NAME_ACTUAL}"
+    @RMMOD@ "${TARGET_NAME_ACTUAL}"
     if test $? -ne 0; then
         printf "Failed to unload the target module: ${TARGET_NAME}\n"
         cleanupAll
@@ -162,17 +158,18 @@ if test $# -ne 1; then
     exit 1
 fi
 
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
+
 TARGET_DIR=$1
-KEDR_MODULE="@KEDR_INSTALL_PREFIX_KMODULE@/@CORE_NAME@.ko"
 
 TARGET_NAME="test_${TARGET_DIR}"
 TARGET_NAME_ACTUAL=$(echo "${TARGET_NAME}" | tr '-' '_')
 
-TARGET_MODULE="${TARGET_DIR}/${TARGET_NAME}.ko"
+TARGET_MODULE="${TARGET_DIR}/${KERNEL}/${TARGET_NAME}.ko"
 printf "Target module: ${TARGET_MODULE}\n"
 
 PAYLOAD_NAME="test_basics_payload"
-PAYLOAD_MODULE="payload/${PAYLOAD_NAME}.ko"
+PAYLOAD_MODULE="payload/${KERNEL}/${PAYLOAD_NAME}.ko"
 
 ################################
 checkPrereqs
diff --git a/sources/tests/core/payload_api/in_init/test.sh.in b/sources/tests/core/payload_api/in_init/test.sh.in
--- a/sources/tests/core/payload_api/in_init/test.sh.in
+++ b/sources/tests/core/payload_api/in_init/test.sh.in
@@ -11,20 +11,16 @@
 # <in_atomic> specifies whether that call should be made from atomic context
 # (!= 0) or not (== 0).
 ########################################################################
-
-# Just in case the tools like lsmod are not in their usual location.
-export PATH=$PATH:/sbin:/bin:/usr/bin
-
 ########################################################################
 # A function to check prerequisites: whether the necessary files exist,
 # etc.
 ########################################################################
 checkPrereqs()
 {
-    if test ! -f "${KEDR_MODULE}"; then
-        printf "KEDR core module is missing: ${KEDR_MODULE}\n"
-        exit 1
-    fi
+    #if test ! -f "${KEDR_MODULE}"; then
+    #    printf "KEDR core module is missing: ${KEDR_MODULE}\n"
+    #    exit 1
+    #fi
     
     if test ! -f "${TARGET_MODULE}"; then
         printf "Target module is missing: ${TARGET_MODULE}\n"
@@ -44,21 +40,21 @@ cleanupAll()
 {
     cd "${WORK_DIR}"
     
-    lsmod | grep "${TARGET_NAME}" > /dev/null 2>&1
+    @LSMOD@ | grep "${TARGET_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
         cd "${TARGET_NAME}"
         sh ./target_unload.sh
         cd "${WORK_DIR}"
     fi
     
-    lsmod | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
+    @LSMOD@ | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "${PAYLOAD_NAME}"
+        @RMMOD@ "${PAYLOAD_NAME}"
     fi
     
-    lsmod | grep "@CORE_NAME@" > /dev/null 2>&1
+    @LSMOD@ | grep "@KEDR_CORE_NAME@" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "@CORE_NAME@"
+        @RMMOD@ "@KEDR_CORE_NAME@"
     fi
 }
 
@@ -67,9 +63,9 @@ cleanupAll()
 ########################################################################
 doTest()
 {
-    insmod "${KEDR_MODULE}" target_name="${TARGET_NAME}" || exit 1
+    @KEDR_CORE_LOAD_COMMAND@ target_name="${TARGET_NAME}" || exit 1
 
-    insmod "${PAYLOAD_MODULE}"
+    @INSMOD@ "${PAYLOAD_MODULE}"
     if test $? -ne 0; then
         printf "Failed to load the payload module\n"
         cleanupAll
@@ -83,14 +79,14 @@ doTest()
         exit 1
     fi
 
-    insmod "${TARGET_MODULE}" in_init=${IN_INIT} in_atomic=${IN_ATOMIC}
+    @INSMOD@ "${TARGET_MODULE}" in_init=${IN_INIT} in_atomic=${IN_ATOMIC}
     if test $? -ne 0; then
         printf "Failed to load the target module: ${TARGET_MODULE}\n"
         cleanupAll
         exit 1
     fi
 
-    rmmod "${TARGET_NAME}"
+    @RMMOD@ "${TARGET_NAME}"
     if test $? -ne 0; then
         printf "Failed to unload the target module: ${TARGET_NAME}\n"
         cleanupAll
@@ -100,14 +96,14 @@ doTest()
     # Save the result to be analyzed below
     RESULT_IN_INIT=$(cat "${OUT_PARAM_FILE}")
 
-    rmmod "${PAYLOAD_NAME}"
+    @RMMOD@ "${PAYLOAD_NAME}"
     if test $? -ne 0; then
         printf "Failed to unload the payload module: ${PAYLOAD_NAME}\n"
         cleanupAll
         exit 1
     fi
 
-    rmmod "@CORE_NAME@" || exit 1
+    @RMMOD@ "@KEDR_CORE_NAME@" || exit 1
     
     # Check the saved result
     printf "Expected value of target_in_init flag is '${IN_INIT}', "
@@ -127,21 +123,21 @@ if test $# -ne 2; then
     exit 1
 fi
 
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
+
 IN_INIT=$1
 IN_ATOMIC=$2
 printf "Mode: in_init=${IN_INIT}, in_atomic=${IN_ATOMIC}\n"
 
-KEDR_MODULE="@KEDR_INSTALL_PREFIX_KMODULE@/@CORE_NAME@.ko"
-
 TARGET_NAME="test_in_init_target"
-TARGET_MODULE="target/${TARGET_NAME}.ko"
+TARGET_MODULE="target/${KERNEL}/${TARGET_NAME}.ko"
 
 PAYLOAD_NAME="test_in_init_payload"
-PAYLOAD_MODULE="payload/${PAYLOAD_NAME}.ko"
+PAYLOAD_MODULE="payload/${KERNEL}/${PAYLOAD_NAME}.ko"
 
 checkPrereqs
 
-printf "Kedr core module: ${KEDR_MODULE}\n"
+printf "Kedr core module: @KEDR_CORE_REF@\n"
 printf "Target module: ${TARGET_MODULE}\n"
 printf "Payload module: ${PAYLOAD_MODULE}\n"
 
diff --git a/sources/tests/core/payload_api/register/test.sh.in b/sources/tests/core/payload_api/register/test.sh.in
--- a/sources/tests/core/payload_api/register/test.sh.in
+++ b/sources/tests/core/payload_api/register/test.sh.in
@@ -21,20 +21,16 @@
 # Loading of the payload module must succeed in each scenario. The result of 
 # the test is output via "test_passed" parameter (see sysfs).
 ########################################################################
-
-# Just in case the tools like lsmod are not in their usual location.
-export PATH=$PATH:/sbin:/bin:/usr/bin
-
 ########################################################################
 # A function to check prerequisites: whether the necessary files exist,
 # etc.
 ########################################################################
 checkPrereqs()
 {
-    if test ! -f "${KEDR_MODULE}"; then
-        printf "KEDR core module is missing: ${KEDR_MODULE}\n"
-        exit 1
-    fi
+    #if test ! -f "${KEDR_MODULE}"; then
+    #    printf "KEDR core module is missing: ${KEDR_MODULE}\n"
+    #    exit 1
+    #fi
     
     if test ! -f "${PAYLOAD_MODULE}"; then
         printf "Payload module is missing: ${PAYLOAD_MODULE}\n"
@@ -49,14 +45,14 @@ cleanupAll()
 {
     cd "${WORK_DIR}"
     
-    lsmod | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
+    @LSMOD@ | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "${PAYLOAD_NAME}"
+        @RMMOD@ "${PAYLOAD_NAME}"
     fi
     
-    lsmod | grep "@CORE_NAME@" > /dev/null 2>&1
+    @LSMOD@ | grep "@KEDR_CORE_NAME@" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "@CORE_NAME@"
+        @RMMOD@ "@KEDR_CORE_NAME@"
     fi
 }
 
@@ -65,9 +61,9 @@ cleanupAll()
 ########################################################################
 doTest()
 {
-    insmod "${KEDR_MODULE}" || exit 1
+    @KEDR_CORE_LOAD_COMMAND@ || exit 1
 
-    insmod "${PAYLOAD_MODULE}" scenario_number=${SCEN_NO}
+    @INSMOD@ "${PAYLOAD_MODULE}" scenario_number=${SCEN_NO}
     if test $? -ne 0; then
         printf "Failed to load the payload module\n"
         cleanupAll
@@ -84,14 +80,14 @@ doTest()
     # Save the result to be analyzed below
     TEST_PASSED=$(cat "${OUT_PARAM_FILE}")
 
-    rmmod "${PAYLOAD_NAME}"
+    @RMMOD@ "${PAYLOAD_NAME}"
     if test $? -ne 0; then
         printf "Failed to unload the payload module: ${PAYLOAD_NAME}\n"
         cleanupAll
         exit 1
     fi
 
-    rmmod "@CORE_NAME@" || exit 1
+    @RMMOD@ "@KEDR_CORE_NAME@" || exit 1
     
     # Check the saved result
     printf "Test result (1 - passed, other value - failed): ${TEST_PASSED}\n"
@@ -110,13 +106,13 @@ if test $# -ne 1; then
     exit 1
 fi
 
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
+
 SCEN_NO=$1
 printf "Scenario number is ${SCEN_NO}\n"
 
-KEDR_MODULE="@KEDR_INSTALL_PREFIX_KMODULE@/@CORE_NAME@.ko"
-
 PAYLOAD_NAME="test_reg_payload"
-PAYLOAD_MODULE="payload/${PAYLOAD_NAME}.ko"
+PAYLOAD_MODULE="payload/${KERNEL}/${PAYLOAD_NAME}.ko"
 
 checkPrereqs
 
diff --git a/sources/tests/core/simple/ins_rm.sh.in b/sources/tests/core/simple/ins_rm.sh.in
--- a/sources/tests/core/simple/ins_rm.sh.in
+++ b/sources/tests/core/simple/ins_rm.sh.in
@@ -3,26 +3,23 @@
 ########################################################################
 # This test checks the basic operations with the KEDR core module.
 ########################################################################
-KEDR_MODULE="@KEDR_INSTALL_PREFIX_KMODULE@/@CORE_NAME@.ko"
-printf "KEDR core module: ${KEDR_MODULE}\n"
+printf "KEDR core module: @KEDR_CORE_REF@\n"
 
-# Just in case the tools like lsmod are not in their usual location.
-export PATH=$PATH:/sbin:/bin:/usr/bin
+# Cannot check existence of kernel module if it is given by name only.
+#if test ! -f "${KEDR_MODULE}"; then
+#    printf "KEDR core module is missing: ${KEDR_MODULE}\n"
+#    
+#    # test failed
+#    exit 1
+#fi
 
-if test ! -f "${KEDR_MODULE}"; then
-    printf "KEDR core module is missing: ${KEDR_MODULE}\n"
-    
-    # test failed
-    exit 1
-fi
-
-insmod "${KEDR_MODULE}"
+@KEDR_CORE_LOAD_COMMAND@
 if test $? -ne 0; then
     printf "Failed to load the KEDR core module\n"
     exit 1
 fi
 
-rmmod "@CORE_NAME@"
+@RMMOD@ "@KEDR_CORE_NAME@"
 if test $? -ne 0; then
     printf "Failed to unload the KEDR core module\n"
     exit 1
diff --git a/sources/tests/core/simple/ins_rm_with_target.sh.in b/sources/tests/core/simple/ins_rm_with_target.sh.in
--- a/sources/tests/core/simple/ins_rm_with_target.sh.in
+++ b/sources/tests/core/simple/ins_rm_with_target.sh.in
@@ -9,19 +9,17 @@
 # latter reports error as it should.
 ########################################################################
 
-# Just in case the tools like lsmod are not in their usual location.
-export PATH=$PATH:/sbin:/bin:/usr/bin
-
 ########################################################################
 # A function to check prerequisites: whether the necessary files exist,
 # etc.
 ########################################################################
 checkPrereqs()
 {
-    if test ! -f "${KEDR_MODULE}"; then
-        printf "KEDR core module is missing: ${KEDR_MODULE}\n"
-        exit 1
-    fi
+    # 'test -f' cannot check existing of module if it is given by name.
+    #if test ! -f "${KEDR_MODULE}"; then
+    #    printf "KEDR core module is missing: ${KEDR_MODULE}\n"
+    #    exit 1
+    #fi
     
     if test ! -f "${PAYLOAD_MODULE}"; then
         printf "Payload module is missing: ${PAYLOAD_MODULE}\n"
@@ -34,22 +32,19 @@ checkPrereqs()
 ########################################################################
 cleanupAll()
 {
-    cd "${WORK_DIR}"
-    
-    lsmod | grep "${TARGET_NAME}" > /dev/null 2>&1
+    @LSMOD@ | grep "${TARGET_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
-        ${TARGET_UNLOAD_CMD}
-        cd "${WORK_DIR}"
+        sh @TEST_MODULES_DIR@/sample_target/${KERNEL}/kedr_sample_target unload
     fi
     
-    lsmod | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
+    @LSMOD@ | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "${PAYLOAD_NAME}"
+        @RMMOD@ "${PAYLOAD_NAME}"
     fi
     
-    lsmod | grep "@CORE_NAME@" > /dev/null 2>&1
+    @LSMOD@ | grep "@KEDR_CORE_NAME@" > /dev/null 2>&1
     if test $? -eq 0; then
-        rmmod "@CORE_NAME@"
+        @RMMOD@ "@KEDR_CORE_NAME@"
     fi
 }
 ########################################################################
@@ -66,16 +61,16 @@ checkCommonScenario()
 {
     printf "Executing checkCommonScenario()\n"
     
-    insmod "${KEDR_MODULE}" target_name="${TARGET_NAME}" || exit 1
+    @KEDR_CORE_LOAD_COMMAND@ target_name="${TARGET_NAME}" || exit 1
 
-    insmod "${PAYLOAD_MODULE}"
+    @INSMOD@ "${PAYLOAD_MODULE}"
     if test $? -ne 0; then
         printf "Failed to load the payload module\n"
         cleanupAll
         exit 1
     fi
 
-    ${TARGET_LOAD_CMD}
+    sh @TEST_MODULES_DIR@/sample_target/${KERNEL}/kedr_sample_target load
     if test $? -ne 0; then
         printf "Failed to load the target module: ${TARGET_NAME}.ko\n"
         cleanupAll
@@ -90,7 +85,7 @@ checkCommonScenario()
     fi
 
     printf "Trying to unload the KEDR core while the target is under analysis (must fail)\n"
-    rmmod "@CORE_NAME@"
+    @RMMOD@ "@KEDR_CORE_NAME@"
     if test $? -eq 0; then
         printf "The KEDR core module must have been locked "
         printf "as long as the target module is under analysis\n"
@@ -99,7 +94,7 @@ checkCommonScenario()
     fi
     printf "This error was expected, continuing.\n"
 
-    ${TARGET_UNLOAD_CMD}
+    sh @TEST_MODULES_DIR@/sample_target/${KERNEL}/kedr_sample_target unload
     if test $? -ne 0; then
         printf "Failed to unload the target module: ${TARGET_NAME}.ko\n"
         cleanupAll
@@ -107,14 +102,14 @@ checkCommonScenario()
     fi
     cd "${WORK_DIR}"
 
-    rmmod "${PAYLOAD_NAME}"
+    @RMMOD@ "${PAYLOAD_NAME}"
     if test $? -ne 0; then
         printf "Failed to unload the payload module: ${PAYLOAD_NAME}\n"
         cleanupAll
         exit 1
     fi
 
-    rmmod "@CORE_NAME@"
+    @RMMOD@ "@KEDR_CORE_NAME@"
     if test $? -ne 0; then
         printf "Failed to unload the KEDR core module\n"
         cleanupAll
@@ -132,7 +127,7 @@ checkTargetFirstScenario()
 {
     printf "Executing checkTargetFirstScenario()\n"
     
-    ${TARGET_LOAD_CMD}
+    sh @TEST_MODULES_DIR@/sample_target/${KERNEL}/kedr_sample_target load
     if test $? -ne 0; then
         printf "Failed to load the target module: ${TARGET_NAME}.ko\n"
         cleanupAll
@@ -141,7 +136,7 @@ checkTargetFirstScenario()
 
     printf "Trying to load the KEDR core when the target is already loaded "
     printf "(must fail)\n"
-    insmod "${KEDR_MODULE}" target_name="${TARGET_NAME}"
+    @KEDR_CORE_LOAD_COMMAND@ target_name="${TARGET_NAME}"
     if test $? -eq 0; then
         printf "KEDR core must have failed to load if the target "
         printf "was already loaded at that moment\n"
@@ -150,7 +145,7 @@ checkTargetFirstScenario()
     fi
     printf "This error was expected, continuing.\n"
 
-    ${TARGET_UNLOAD_CMD}
+    sh @TEST_MODULES_DIR@/sample_target/${KERNEL}/kedr_sample_target unload
     if test $? -ne 0; then
         printf "Failed to unload the target module: ${TARGET_NAME}.ko\n"
         cleanupAll
@@ -170,19 +165,17 @@ if test $# -ne 1; then
     exit 1
 fi
 
-KEDR_MODULE="@KEDR_INSTALL_PREFIX_KMODULE@/@CORE_NAME@.ko"
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
 
 TARGET_NAME="@TARGET_NAME@"
-TARGET_LOAD_CMD="@TARGET_LOAD_CMD@"
-TARGET_UNLOAD_CMD="@TARGET_UNLOAD_CMD@"
 
 PAYLOAD_NAME="simple_payload"
-PAYLOAD_MODULE="${PAYLOAD_NAME}/${PAYLOAD_NAME}.ko"
+PAYLOAD_MODULE="${PAYLOAD_NAME}/${KERNEL}/${PAYLOAD_NAME}.ko"
 
 checkPrereqs
 
-printf "KEDR core module: ${KEDR_MODULE}\n"
-printf "Target module: ${TARGET_NAME}.ko\n"
+printf "KEDR core module: @KEDR_CORE_NAME@\n"
+printf "Target module: @TEST_MODULES_DIR@/sample_target/${KERNEL}/${TARGET_NAME}.ko\n"
 printf "Payload module: ${PAYLOAD_MODULE}\n"
 
 # Select the test scenario
diff --git a/sources/tests/examples/sample_fsim/test_fault_simulation.sh.in b/sources/tests/examples/sample_fsim/test_fault_simulation.sh.in
--- a/sources/tests/examples/sample_fsim/test_fault_simulation.sh.in
+++ b/sources/tests/examples/sample_fsim/test_fault_simulation.sh.in
@@ -1,20 +1,21 @@
 #!/bin/sh
 
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
+
 debugfs_mount_point="@KEDR_TEST_DIR@/debugfs"
 point_name=__kmalloc
 indicator_name=periodic
 
 point_dir=${debugfs_mount_point}/kedr_fault_simulation/points/${point_name}
 
-sample_indicator_test_location=@sample_indicator_test_location@
-sample_fsim_payload_test_location=@sample_fsim_payload_test_location@
+sample_indicator_test_location=@sample_indicator_test_location@/${KERNEL}
+sample_fsim_payload_test_location=@sample_fsim_payload_test_location@/${KERNEL}
 
 fsim_payload_module="$sample_fsim_payload_test_location/kedr_sample_fsim_payload.ko"
 indicator_module="$sample_indicator_test_location/kedr_sample_indicator.ko"
-kedr_fault_simulation_module="@KEDR_INSTALL_PREFIX_KMODULE@/kedr_fault_simulation.ko"
 
 sample_target_module_name=kedr_sample_target
-sample_target_script="sh @TEST_MODULES_DIR@/sample_target/kedr_sample_target"
+sample_target_script="sh @TEST_MODULES_DIR@/sample_target/${KERNEL}/kedr_sample_target"
 sample_target_device="/dev/cfake0"
 
 kedr_conf_file="./kedr.conf"
@@ -24,7 +25,7 @@ kedr_control_script="sh @KEDR_INSTALL_PREFIX_EXEC@/kedr"
 do_commands_script="sh @TEST_SCRIPTS_DIR@/do_commands.sh"
 
 cat > "$kedr_conf_file" << eof
-module ${kedr_fault_simulation_module}
+module @KEDR_FAULT_SIMULATION_REF@
 payload ${fsim_payload_module}
 module ${indicator_module}
 eof
@@ -47,16 +48,16 @@ if ! ./build_payload.sh $sample_fsim_payload_test_location; then
 fi
 
 if ! $do_commands_script "$commands_file" load; then
-	printf "Cannot initialize test.\n"
-	exit 1
+    printf "Cannot initialize test.\n"
+    exit 1
 fi
 # Set indicator with "always simulate fail" scenario
 printf "${indicator_name} 1" > "${point_dir}/current_indicator"
 
 if test $? -ne 0; then
-	printf "Cannot set indicator for the point.\n"
-	$do_commands_script "$commands_file" unload
-	exit 1
+    printf "Cannot set indicator for the point.\n"
+    $do_commands_script "$commands_file" unload
+    exit 1
 fi
 
 #Try to load target module
@@ -68,16 +69,16 @@ if test $? -eq 0; then
     printf "but it was successfully loaded.\n"
     ${sample_target_script} unload
     $do_commands_script "$commands_file" unload
-	exit 1
+    exit 1
 fi
 
 # Set indicator with "simulate fail every second call" scenario
 printf "${indicator_name} 2" > "${point_dir}/current_indicator"
 
 if test $? -ne 0; then
-	printf "Cannot set indicator for the point again.\n"
-	$do_commands_script "$commands_file" unload
-	exit 1
+    printf "Cannot set indicator for the point again.\n"
+    $do_commands_script "$commands_file" unload
+    exit 1
 fi
 
 #Now target module should be successfully loaded
@@ -87,7 +88,7 @@ ${sample_target_script} load
 if test $? -ne 0; then
     printf "Target module should be loaded successfully with \"fail every second call\" fault simulation scenario.\n"
     $do_commands_script "$commands_file" unload
-	exit 1
+    exit 1
 fi
 
 #But writing to the device should fail
@@ -98,12 +99,12 @@ result=$?
 ${sample_target_script} unload
 
 if test "$result" -eq 0; then
-	printf "It was expected that writing to the device created by sample target would fail but it succeeded.\n"
-	$do_commands_script "$commands_file" unload
-	exit 1
+    printf "It was expected that writing to the device created by sample target would fail but it succeeded.\n"
+    $do_commands_script "$commands_file" unload
+    exit 1
 fi
 
 if ! $do_commands_script "$commands_file" unload; then
-	printf "Errors occured while finalizing the test.\n"
-	exit 1
+    printf "Errors occured while finalizing the test.\n"
+    exit 1
 fi
diff --git a/sources/tests/fault_simulation/test_fault_tolerance.sh.in b/sources/tests/fault_simulation/test_fault_tolerance.sh.in
--- a/sources/tests/fault_simulation/test_fault_tolerance.sh.in
+++ b/sources/tests/fault_simulation/test_fault_tolerance.sh.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-fault_simulation_module="@KEDR_INSTALL_PREFIX_KMODULE@/kedr_fault_simulation.ko"
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
 
 read_point_name="kedr-read-point"
 write_point_name="kedr-write-point"
@@ -8,8 +8,9 @@ read_indicator_name="indicator_for_read"
 write_indicator_name="indicator_for_write"
 
 module_a_name="fsim_test_module_a"
-module_a="module_a/${module_a_name}.ko"
-module_b="module_b/fsim_test_module_b.ko"
+module_a="module_a/${KERNEL}/${module_a_name}.ko"
+module_b_name="fsim_test_module_b"
+module_b="module_b/${KERNEL}/${module_b_name}.ko"
 current_value_file="/sys/module/${module_a_name}/parameters/current_value"
 
 device=kedr_test_device
@@ -54,8 +55,8 @@ do_commands_script="sh @TEST_SCRIPTS_DIR@/do_commands.sh"
 
 cat > "$commands_file" << eof
 
-on_load insmod "$fault_simulation_module" || ! printf "Cannot load fault simulation module into kernel.\n"
-on_unload rmmod "$fault_simulation_module" || ! printf "Cannot unload fault simulation module.\n"
+on_load @KEDR_FAULT_SIMULATION_LOAD_COMMAND@ || ! printf "Cannot load fault simulation module into kernel.\n"
+on_unload @RMMOD@ "@KEDR_FAULT_SIMULATION_NAME@" || ! printf "Cannot unload fault simulation module.\n"
 on_load mkdir -p "$debugfs_mount_point" || ! printf "Cannot create mount point for debugfs.\n"
 on_load mount -t debugfs debugfs "$debugfs_mount_point" || ! printf "Cannot mount debugfs.\n"
 on_unload umount "$debugfs_mount_point" || ! printf "Error occured while umounting debugfs.\n"
@@ -63,8 +64,8 @@ eof
 
 cat > "$commands_file_module_a" << eof
 
-on_load insmod "$module_a" || ! printf "Cannot load module 'a' into the kernel.\n"
-on_unload rmmod "$module_a" || ! printf "Fail to unload module 'a'.\n"
+on_load @INSMOD@ "$module_a" || ! printf "Cannot load module 'a' into the kernel.\n"
+on_unload @RMMOD@ "$module_a_name" || ! printf "Fail to unload module 'a'.\n"
 
 eof
 
@@ -79,7 +80,7 @@ if ! $do_commands_script "$commands_file_module_a" load; then
 fi
 
 
-if ! insmod "$module_b"; then
+if ! @INSMOD@ "$module_b"; then
     printf "Cannot load module 'b' into the kernel.\n"
     $do_commands_script "$commands_file_module_a" unload && $do_commands_script "$commands_file" unload
     exit 1
@@ -89,7 +90,7 @@ fi
 
 if set_indicator "$read_point_name" "$write_indicator_name"; then
     printf "Indicator was set for a point which data it cannot process.\n"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file_module_a" unload    
     $do_commands_script "$commands_file" unload
     
@@ -98,7 +99,7 @@ fi
 
 if ! set_indicator "$read_point_name" "$read_indicator_name"; then
     printf "Cannot set indicator for the point.\n"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     
     $do_commands_script "$commands_file" unload
     
@@ -110,7 +111,7 @@ fi
     # Module 'a' should correctly be unloaded even with file opened
     if ! $do_commands_script "$commands_file_module_a" unload; then
         printf "Cannot remove module 'a' with indicator control file opened.\n"
-        rmmod "$module_b"
+        @RMMOD@ "$module_b_name"
         $do_commands_script "$commands_file" unload
         exit 1
     fi
@@ -120,14 +121,14 @@ fi
     echo "$write_indicator_name"  >&8 
 
     if ! $do_commands_script "$commands_file_module_a" load; then
-	printf "Failed to load module 'a' again.\n"
-	rmmod "$module_b"
-	$do_commands_script "$commands_file" unload
-	exit 1
+        printf "Failed to load module 'a' again.\n"
+        @RMMOD@ "$module_b_name"
+        $do_commands_script "$commands_file" unload
+        exit 1
     fi
 
 } 9<"$control_root/points/${read_point_name}/current_indicator" 8>"$control_root/points/${read_point_name}/current_indicator"
 
-rmmod "$module_b" && \
+@RMMOD@ "$module_b_name" && \
     $do_commands_script "$commands_file_module_a" unload && \
     $do_commands_script "$commands_file" unload
diff --git a/sources/tests/fault_simulation/test_simple.sh.in b/sources/tests/fault_simulation/test_simple.sh.in
--- a/sources/tests/fault_simulation/test_simple.sh.in
+++ b/sources/tests/fault_simulation/test_simple.sh.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-fault_simulation_module="@KEDR_INSTALL_PREFIX_KMODULE@/kedr_fault_simulation.ko"
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
 
 read_point_name="kedr-read-point"
 write_point_name="kedr-write-point"
@@ -8,9 +8,11 @@ read_indicator_name="indicator_for_read"
 write_indicator_name="indicator_for_write"
 
 module_a_name="fsim_test_module_a"
-module_a="module_a/${module_a_name}.ko"
-module_b="module_b/fsim_test_module_b.ko"
-indicators_simple="indicators_simple/fsim_test_indicators_simple.ko"
+module_a="module_a/${KERNEL}/${module_a_name}.ko"
+module_b_name="fsim_test_module_b"
+module_b="module_b/${KERNEL}/${module_b_name}.ko"
+indicators_simple_name=fsim_test_indicators_simple
+indicators_simple="indicators_simple/${KERNEL}/${indicators_simple_name}.ko"
 current_value_file="/sys/module/${module_a_name}/parameters/current_value"
 
 device=kedr_test_device
@@ -75,13 +77,13 @@ do_commands_script="@TEST_SCRIPTS_DIR@/do_commands.sh"
 
 cat > "$commands_file" << eof
 
-on_load insmod "$fault_simulation_module" || ! printf "Cannot load fault simulation module into kernel.\n"
-on_unload rmmod "$fault_simulation_module" || ! printf "Cannot unload fault simulation module.\n"
+on_load @KEDR_FAULT_SIMULATION_LOAD_COMMAND@ || ! printf "Cannot load fault simulation module into kernel.\n"
+on_unload @RMMOD@ @KEDR_FAULT_SIMULATION_NAME@ || ! printf "Cannot unload fault simulation module.\n"
 on_load mkdir -p "$debugfs_mount_point" || ! printf "Cannot create mount point for debugfs.\n"
 on_load mount -t debugfs debugfs "$debugfs_mount_point" || ! printf "Cannot mount debufs.\n"
 on_unload umount "$debugfs_mount_point" || ! printf "Error occured while umounting debufs.\n"
-on_load insmod "$module_a" || ! printf "Cannot load module 'a' into kernel.\n"
-on_unload rmmod "$module_a" || ! printf "Failed to unload module 'a'.\n"
+on_load @INSMOD@ "$module_a" || ! printf "Cannot load module 'a' into kernel.\n"
+on_unload @RMMOD@ "$module_a_name" || ! printf "Failed to unload module 'a'.\n"
 
 eof
 
@@ -112,7 +114,7 @@ if ! check_last_fault "none"; then
     exit 1
 fi
 
-if ! insmod "$module_b"; then
+if ! @INSMOD@ "$module_b"; then
     printf "Cannot load module 'b' into kernel.\n"
     $do_commands_script "$commands_file" unload
     exit 1
@@ -122,7 +124,7 @@ fi
 
 if ! set_indicator "$read_point_name" "$read_indicator_name"; then
     printf "Cannot set indicator for read point.\n"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
@@ -132,13 +134,13 @@ simulate_point "$read_point_name"
 
 if test "$current_value" != "9"; then
     printf "The simulation of read point was expected to return '9' but it returned '%s'.\n" "$current_value"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
 
 if ! check_last_fault "Read: 9"; then
-    rmmod "$module_b"
+    @RMMOD@ "$module_b"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
@@ -146,7 +148,7 @@ fi
 
 if ! set_indicator "$write_point_name" "$write_indicator_name"; then
     printf "Cannot set indicator for write point.\n"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
@@ -156,13 +158,13 @@ simulate_point "$write_point_name" 25
 
 if test "$current_value" != "25"; then
     printf "The simulation of write point was expected to return '25'(size) but it returned '%s'.\n" "$current_value"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
 
 if ! check_last_fault "Write for 25: 25"; then
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
@@ -171,7 +173,7 @@ fi
 #Rewrite indicator for write point
 if ! set_indicator "$write_point_name" "$read_indicator_name"; then
     printf "Cannot set read indicator for write point.\n"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
@@ -181,14 +183,14 @@ simulate_point "$write_point_name" 25
 
 if test "$current_value" != "9"; then
     printf "The simulation of write point with read indicator was expected to return '9' but it returned '%s'.\n" "$current_value"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
 
 if ! check_last_fault "Write for 25: 9"; then
     $do_commands_script "$commands_file" unload
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     exit 1
 fi
 
@@ -205,7 +207,7 @@ fi
 current_indicator=`get_indicator "$read_point_name"`
 if test "$current_indicator" != "none"; then
     printf "'current_indicator' file for read point conatins '%s', but should be 'none'\n" "$current_indicator"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
@@ -215,12 +217,12 @@ simulate_point "$read_point_name"
 
 if test "$current_value" != "0"; then
     printf "The simulation of read point was expected to return '0' (indicator was cleared) but it returned '%s'.\n" "$current_value"
-    rmmod "$module_b"
+    @RMMOD@ "$module_b_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
 
-if ! rmmod "$module_b"; then
+if ! @RMMOD@ "$module_b_name"; then
     printf "Cannot unload module_b.\n"
     exit 1
 fi
@@ -244,7 +246,7 @@ fi
 
 # Set "never" and "always" scenarious
 
-if ! insmod "$indicators_simple"; then
+if ! @INSMOD@ "$indicators_simple"; then
     printf "Cannot load module with simple indicators into kernel.\n"
     $do_commands_script "$commands_file" unload
     exit 1
@@ -252,8 +254,8 @@ fi
 
 
 if ! set_indicator "$read_point_name" "never"; then
-    printf "Cannot set "never" scenario for read point.\n"
-    rmmod "$indicators_simple"
+    printf "Cannot set \"never\" scenario for read point.\n"
+    @RMMOD@ "$indicators_simple_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
@@ -262,14 +264,14 @@ simulate_point "$read_point_name"
 
 if test "$current_value" != 0 ; then
     printf "The simulation for read point was expected to return '0' (scenario is 'never') but it returned '%s'.\n" "$current_value"
-	rmmod "$indicators_simple"
+	@RMMOD@ "$indicators_simple_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
 
 if ! set_indicator "$read_point_name" "always"; then
     printf "Cannot set \"always\" scenario for read point.\n"
-    rmmod "$indicators_simple"
+    @RMMOD@ "$indicators_simple_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
@@ -278,12 +280,12 @@ simulate_point "$read_point_name"
 
 if test "$current_value" != 1 ; then
     printf "The simulation for read point was expected to return '1' (scenario is 'always') but it returned '%s'.\n" "$current_value"
-	rmmod "$indicators_simple"
+	@RMMOD@ "$indicators_simple_name"
     $do_commands_script "$commands_file" unload
     exit 1
 fi
 
-if ! rmmod "$indicators_simple"; then
+if ! @RMMOD@ "$indicators_simple_name"; then
     printf "Cannot unload module with simple indicators.\n"
     exit 1
 fi
diff --git a/sources/tests/payloads_fsim/final_template/test_common.sh.in b/sources/tests/payloads_fsim/final_template/test_common.sh.in
--- a/sources/tests/payloads_fsim/final_template/test_common.sh.in
+++ b/sources/tests/payloads_fsim/final_template/test_common.sh.in
@@ -1,20 +1,54 @@
-# Common declaration for tests
-# debugfs_mount_point should be declared at this stage
+# Common test script.
+#
+# Usage:
+#
+#  test.common.sh <test_definition_script>
+#
+# Script <test_definition_script> should define next variables:
+#
+# - tmpdir: directory with temporary files for test. It will be created automatically.
+# - payload_fsim: fault simulation payload which is tested.
+#
+# Also <test_definition_script> should define function test_function(),
+# it wil be executed when all initialization is performed.
 
-fault_simulation_module="@KEDR_INSTALL_PREFIX_KMODULE@/kedr_fault_simulation.ko"
+
+if test $# -eq 0; then
+	printf "Test definition script should be given\n"
+	exit 1
+fi
+
+# Definitions which will be visible for common part of included script.
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
+
+indicator_constant_name="constant"
+indicator_greater_than_name="greater_than"
+
+
+. $1
+
+if test -z "$tmpdir"; then
+	printf "Test definition script did not define 'tmpdir' variable.\n"
+	exit 1
+fi
+
+if test -z "$payload_fsim"; then
+	printf "Test definition script did not define 'payload_fsim' variable.\n"
+	exit 1
+fi
+
+
+# These definitions may be used inside test_function() in included script.
+debugfs_mount_point="${tmpdir}/debugfs"
 fault_simulation_points_dir="${debugfs_mount_point}/kedr_fault_simulation/points"
 
 trigger_target_module_name="@trigger_target_module_name@"
-trigger_target="@this_install_dir@/trigger_target/${trigger_target_module_name}.ko"
+trigger_target="@this_install_dir@/trigger_target/${KERNEL}/${trigger_target_module_name}.ko"
 trigger_target_control_dir="${debugfs_mount_point}/function_triggers"
 
-indicator_constant="@this_install_dir@/indicator_constant/@indicator_constant_module_name@.ko"
-indicator_constant_name="constant"
+indicators_module_name=@indicators_module_name@
+indicators_module="@this_install_dir@/indicators_module/${KERNEL}/${indicators_module_name}.ko"
 
-indicator_greater_than="@this_install_dir@/indicator_greater_than/@indicator_greater_than_module_name@.ko"
-indicator_greater_than_name="greater_than"
-
-kedr_core_module="@KEDR_INSTALL_PREFIX_KMODULE@/kedr.ko"
 
 do_commands_script="sh @TEST_SCRIPTS_DIR@/do_commands.sh"
 
@@ -23,3 +57,52 @@ trigger_function()
 {
 	dd "bs=$2" count=1 if=/dev/zero "of=${trigger_target_control_dir}/$1"
 }
+
+
+############################## Initialization part #####################
+mkdir -p "${tmpdir}"
+
+commands_file="${tmpdir}/commands"
+
+cat > "$commands_file" << eof
+
+on_load @KEDR_FAULT_SIMULATION_LOAD_COMMAND@ || ! printf "Cannot load fault simulation module into kernel.\n"
+on_unload @RMMOD@ "@KEDR_FAULT_SIMULATION_NAME@" || ! printf "Cannot unload fault simulation module.\n"
+
+on_load @KEDR_CORE_LOAD_COMMAND@ target_name="${trigger_target_module_name}" || ! printf "Cannot load KEDR core module.\n"
+on_unload @RMMOD@ "@KEDR_CORE_NAME@" || ! printf "Cannot unload KEDR core module.\n"
+
+on_load @INSMOD@ "${payload_fsim}" || ! printf "Cannot load generated fault simulation payload into kernel.\n"
+on_unload @RMMOD@ "${payload_fsim}" || ! printf "Cannot unload generated fault simulation payload.\n"
+
+on_load mkdir -p "$debugfs_mount_point" || ! printf "Cannot create mount point for debugfs.\n"
+on_load mount -t debugfs debugfs "$debugfs_mount_point" || ! printf "Cannot mount debugfs.\n"
+on_unload umount "$debugfs_mount_point" || ! printf "Error occured while umounting debugfs.\n"
+
+on_load @INSMOD@ "${indicators_module}" || ! printf "Cannot load fault simulation indicators for test.\n"
+on_unload @RMMOD@ "${indicators_module}" || ! printf "Cannot unload fault simulation indicators.\n"
+
+on_load @INSMOD@ "${trigger_target}" || ! printf "Cannot load target module for trigger functions into kernel.\n"
+on_unload @RMMOD@ "${trigger_target}" || ! printf "Cannot unload target module for trigger functions.\n"
+
+eof
+
+if ! $do_commands_script "$commands_file" load; then
+    printf "Cannot initialize test.\n"
+    exit 1
+fi
+
+########################################################################
+test_function
+
+test_result=$?
+if test ${test_result} -ne 0; then
+	$do_commands_script "$commands_file" unload
+	exit ${test_result}
+fi
+##################### Finalization part ################################
+if ! $do_commands_script "$commands_file" unload; then
+	printf "Error occures while finalize test.\n"
+	
+	exit 1
+fi
diff --git a/sources/tests/tools/capture_trace/test_block.sh.in b/sources/tests/tools/capture_trace/test_block.sh.in
--- a/sources/tests/tools/capture_trace/test_block.sh.in
+++ b/sources/tests/tools/capture_trace/test_block.sh.in
@@ -2,17 +2,14 @@
 
 # Test kedr_capture_trace functionality in the blocking mode.
 
-# Just in case the tools like lsmod are not in their usual location.
-export PATH=$PATH:/sbin:/bin:/usr/bin
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
 
-kedr_module_name="@CORE_MODULE_NAME@"
-kedr_module="@CORE_MODULE@"
-kedr_trace_module_name="@TRACE_MODULE_NAME@"
-kedr_trace_module="@TRACE_MODULE@"
+kedr_module_name="@KEDR_CORE_NAME@"
+kedr_trace_module_name="@KEDR_TRACE_NAME@"
 payload_module_name=kedr_payload
-payload_module="payload/${payload_module_name}.ko"
+payload_module="payload/${KERNEL}/${payload_module_name}.ko"
 target_module_name=kedr_target
-target_module="target/${target_module_name}.ko"
+target_module="target/${KERNEL}/${target_module_name}.ko"
 
 
 tmpdir="@KEDR_TEST_PREFIX_TEMP_SESSION@/capture_trace_block"
@@ -25,7 +22,7 @@ mkdir -p "${debugfs_mount_point}"
 
 capture_trace_program="@CAPTURE_TRACE_PROGRAM@"
 
-#is_process_running pid
+#  is_process_running pid
 is_process_running()
 {
     nlines=`ps -p "$1" | wc -l`
@@ -33,35 +30,35 @@ is_process_running()
 }
 
 # Load KEDR core and payload modules
-insmod "${kedr_module}" "target_name=${target_module_name}"
+@KEDR_CORE_LOAD_COMMAND@ "target_name=${target_module_name}"
 if test $? -ne 0; then
-	printf "Failed to load KEDR core module for tests\n"
-	exit 1
+    printf "Failed to load KEDR core module for tests\n"
+    exit 1
 fi
 
-insmod "${kedr_trace_module}"
+@KEDR_TRACE_LOAD_COMMAND@ "${kedr_trace_module}"
 if test $? -ne 0; then
-	printf "Failed to load kedr tracing module for tests\n"
-    rmmod "${kedr_module_name}"
-	exit 1
+    printf "Failed to load kedr tracing module for tests\n"
+    @RMMOD@ "${kedr_module_name}"
+    exit 1
 fi
 
 
-insmod "${payload_module}"
+@INSMOD@ "${payload_module}"
 if test $? -ne 0; then
-	printf "Failed to load payload module for tests\n"
-    rmmod "${kedr_trace_module_name}"
-    rmmod "${kedr_module_name}"
-	exit 1
+    printf "Failed to load payload module for tests\n"
+    @RMMOD@ "${kedr_trace_module_name}"
+    @RMMOD@ "${kedr_module_name}"
+    exit 1
 fi
 
 mkdir -p "${debugfs_mount_point}"
 mount debugfs -t debugfs "${debugfs_mount_point}"
 if test $? -ne 0; then
     printf "Cannot mount debugfs.\n"
-    rmmod "${payload_module_name}"
-    rmmod "${kedr_trace_module_name}"
-    rmmod "${kedr_module_name}"
+    @RMMOD@ "${payload_module_name}"
+    @RMMOD@ "${kedr_trace_module_name}"
+    @RMMOD@ "${kedr_module_name}"
     exit 1
 fi
 
@@ -73,28 +70,28 @@ capture_pid=$!
 if ! is_process_running "$capture_pid"; then
     printf "Failed to start capturing\n"
     umount "${debugfs_mount_point}"
-    rmmod "${payload_module_name}"
-    rmmod "${kedr_trace_module_name}"
-    rmmod "${kedr_module_name}"
+    @RMMOD@ "${payload_module_name}"
+    @RMMOD@ "${kedr_trace_module_name}"
+    @RMMOD@ "${kedr_module_name}"
     exit 1
 fi
 # Load target module
 
-insmod "${target_module}"
+@INSMOD@ "${target_module}"
 
 if test $? -ne 0; then
-	printf "Failed to load target module\n"
+    printf "Failed to load target module\n"
     kill $capture_pid
     wait $capture_pid
     umount "${debugfs_mount_point}"
-    rmmod "${payload_module_name}"
-    rmmod "${kedr_trace_module_name}"
-    rmmod "${kedr_module_name}"
-	exit 1
+    @RMMOD@ "${payload_module_name}"
+    @RMMOD@ "${kedr_trace_module_name}"
+    @RMMOD@ "${kedr_module_name}"
+    exit 1
 fi
 
 # Unload target module
-rmmod "${target_module}"
+@RMMOD@ "${target_module_name}"
 sleep 0.5
 
 # Stop capturing
@@ -106,9 +103,9 @@ wait "$capture_pid"
 umount "${debugfs_mount_point}"
 
 #Unload payload and KEDR core and other modules
-rmmod "${payload_module}"
-rmmod "${kedr_trace_module_name}"
-rmmod "${kedr_module}"
+@RMMOD@ "${payload_module_name}"
+@RMMOD@ "${kedr_trace_module_name}"
+@RMMOD@ "${kedr_module_name}"
 
 #Verify trace existance
 if ! test -f "${trace_file}"; then
diff --git a/sources/tests/util/stack_trace/reliability/test.sh.in b/sources/tests/util/stack_trace/reliability/test.sh.in
--- a/sources/tests/util/stack_trace/reliability/test.sh.in
+++ b/sources/tests/util/stack_trace/reliability/test.sh.in
@@ -10,17 +10,14 @@
 #   sh test.sh
 ########################################################################
 
-# Just in case the tools like lsmod are not in their usual location.
-export PATH=$PATH:/sbin:/bin:/usr/bin
-
 ########################################################################
 # A function to check prerequisites: whether the necessary files exist,
 # etc.
 ########################################################################
 checkPrereqs()
 {
-    if test ! -f "${TEST_MODULE}.ko"; then
-        printf "Stack trace module is missing: ${WORK_DIR}/${TEST_MODULE}.ko\n"
+    if test ! -f "${TEST_MODULE}"; then
+        printf "Stack trace module is missing: ${TEST_MODULE}\n"
         exit 1
     fi
 }
@@ -30,7 +27,7 @@ checkPrereqs()
 ########################################################################
 cleanupAll()
 {
-    rmmod "${TEST_MODULE}" || true
+    @RMMOD@ "${TEST_MODULE_NAME}" || true
 }
 
 ########################################################################
@@ -38,14 +35,14 @@ cleanupAll()
 ########################################################################
 doTest()
 {
-    insmod "${TEST_MODULE}.ko"
+    @INSMOD@ "${TEST_MODULE}"
     if test $? -ne 0; then
         printf "Failed to load ${TEST_MODULE}\n"
         cleanupAll
         exit 1
     fi
     
-    OUT_PARAM_FILE="/sys/module/${TEST_MODULE}/parameters/stack_frames"
+    OUT_PARAM_FILE="/sys/module/${TEST_MODULE_NAME}/parameters/stack_frames"
     if test ! -e "${OUT_PARAM_FILE}"; then
         printf "Parameter file does not exist: ${OUT_PARAM_FILE}\n"
         cleanupAll
@@ -82,7 +79,10 @@ if test $# -ne 0; then
     exit 1
 fi
 
-TEST_MODULE=@KMODULE_NAME@
+@multi_kernel_KERNEL_VAR_SHELL_DEFINITION@
+
+TEST_MODULE_NAME=@KMODULE_NAME@
+TEST_MODULE=${KERNEL}/${TEST_MODULE_NAME}.ko
 
 checkPrereqs
 doTest
