Move several tests into corresponded directories with components which are tested by those tests.
Split kedr_base component of KEDR core into kedr_base and kedr_functions_support. Rename kedr_controller component to kedr_instrumentor.

Add tests for KEDR core components.

diff --git a/sources/core/tests/payload_api/register/test.sh.in b/sources/core/tests/payload_api/register/test.sh.in
--- a/sources/core/tests/payload_api/register/test.sh.in
+++ b/sources/core/tests/payload_api/register/test.sh.in
@@ -1,15 +1,25 @@
 #!/bin/sh
 
 ########################################################################
-# This test checks kedr_target_module_in_init() function.
-# Usage: 
-#   sh test.sh <in_init> <in_atomic>
+# This test checks kedr_payload_register() and kedr_payload_unregister().
 #
-# <in_init> specifies whether the call to the target function should be made
-# at the initialization stage of the target module (!= 0) or from the module 
-# core (== 0)
-# <in_atomic> specifies whether that call should be made from atomic context
-# (!= 0) or not (== 0).
+# [NB] The typical use case when these functions are called once and with 
+# correct arguments is implicitly checked, for example, in the tests for 
+# call interception, etc. We need to check some other scenarios here.
+# 
+# Usage: 
+#   sh test.sh <scenario_number>
+#
+# <scenario_number>:
+#   0 - register + unregister, then again register + unregister (with 
+# correct data each time)
+#   1 - attempt to register the same payload twice (the second call must 
+# fail)
+#   2 - register + attempt to unregister some other payload + unregister
+# correctly (must not crash, no explicit checks)
+#
+# Loading of the payload module must succeed in each scenario. The result of 
+# the test is output via "test_passed" parameter (see sysfs).
 ########################################################################
 
 ########################################################################
@@ -20,11 +30,6 @@ checkPrereqs()
 {
     if test ! -f "${KEDR_MODULE}"; then
         printf "KEDR core module is missing: ${KEDR_MODULE}\n"
-        exit 1
-    fi
-    
-    if test ! -f "${TARGET_MODULE}"; then
-        printf "Target module is missing: ${TARGET_MODULE}\n"
         exit 1
     fi
     
@@ -41,21 +46,14 @@ cleanupAll()
 {
     cd "${WORK_DIR}"
     
-    lsmod | grep "${TARGET_NAME}" > /dev/null 2>&1
-    if test $? -eq 0; then
-        cd "${TARGET_NAME}"
-        sh ./target_unload.sh
-        cd "${WORK_DIR}"
-    fi
-    
     lsmod | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
         /sbin/rmmod "${PAYLOAD_NAME}"
     fi
     
-    lsmod | grep "@KEDR_NAME@" > /dev/null 2>&1
+    lsmod | grep "@CORE_NAME@" > /dev/null 2>&1
     if test $? -eq 0; then
-        /sbin/rmmod "@KEDR_NAME@"
+        /sbin/rmmod "@CORE_NAME@"
     fi
 }
 
@@ -64,38 +62,24 @@ cleanupAll()
 ########################################################################
 doTest()
 {
-    /sbin/insmod "${KEDR_MODULE}" target_name="${TARGET_NAME}" || exit 1
+    /sbin/insmod "${KEDR_MODULE}" || exit 1
 
-    /sbin/insmod "${PAYLOAD_MODULE}"
+    /sbin/insmod "${PAYLOAD_MODULE}" scenario_number=${SCEN_NO}
     if test $? -ne 0; then
         printf "Failed to load the payload module\n"
         cleanupAll
         exit 1
     fi
     
-    OUT_PARAM_FILE="/sys/module/${PAYLOAD_NAME}/parameters/target_in_init"
+    OUT_PARAM_FILE="/sys/module/${PAYLOAD_NAME}/parameters/test_passed"
     if test ! -e "${OUT_PARAM_FILE}"; then
         printf "Parameter file does not exist: ${OUT_PARAM_FILE}\n"
         cleanupAll
         exit 1
     fi
 
-    /sbin/insmod "${TARGET_MODULE}" in_init=${IN_INIT} in_atomic=${IN_ATOMIC}
-    if test $? -ne 0; then
-        printf "Failed to load the target module: ${TARGET_MODULE}\n"
-        cleanupAll
-        exit 1
-    fi
-
-    /sbin/rmmod "${TARGET_NAME}"
-    if test $? -ne 0; then
-        printf "Failed to unload the target module: ${TARGET_NAME}\n"
-        cleanupAll
-        exit 1
-    fi
-
     # Save the result to be analyzed below
-    RESULT_IN_INIT=$(cat "${OUT_PARAM_FILE}")
+    TEST_PASSED=$(cat "${OUT_PARAM_FILE}")
 
     /sbin/rmmod "${PAYLOAD_NAME}"
     if test $? -ne 0; then
@@ -104,12 +88,11 @@ doTest()
         exit 1
     fi
 
-    /sbin/rmmod "@KEDR_NAME@" || exit 1
+    /sbin/rmmod "@CORE_NAME@" || exit 1
     
     # Check the saved result
-    printf "Expected value of target_in_init flag is '${IN_INIT}', "
-    printf "actual value is '${RESULT_IN_INIT}'\n"
-    if test "t${RESULT_IN_INIT}" != "t${IN_INIT}"; then
+    printf "Test result (1 - passed, other value - failed): ${TEST_PASSED}\n"
+    if test "t${TEST_PASSED}" != "t1"; then
         exit 1
     fi
 }
@@ -119,27 +102,22 @@ doTest()
 ########################################################################
 WORK_DIR=${PWD}
 
-if test $# -ne 2; then
-    printf "Usage: sh test.sh <in_init> <in_atomic>\n"
+if test $# -ne 1; then
+    printf "Usage: sh test.sh <scenario_number>\n"
     exit 1
 fi
 
-IN_INIT=$1
-IN_ATOMIC=$2
-printf "Mode: in_init=${IN_INIT}, in_atomic=${IN_ATOMIC}\n"
+SCEN_NO=$1
+printf "Scenario number is ${SCEN_NO}\n"
 
-KEDR_MODULE="@KEDR_DIR@/@KEDR_NAME@.ko"
+KEDR_MODULE="@CORE_DIR@/@CORE_NAME@.ko"
 
-TARGET_NAME="test_in_init_target"
-TARGET_MODULE="target/${TARGET_NAME}.ko"
-
-PAYLOAD_NAME="test_in_init_payload"
+PAYLOAD_NAME="test_reg_payload"
 PAYLOAD_MODULE="payload/${PAYLOAD_NAME}.ko"
 
 checkPrereqs
 
 printf "Kedr core module: ${KEDR_MODULE}\n"
-printf "Target module: ${TARGET_MODULE}\n"
 printf "Payload module: ${PAYLOAD_MODULE}\n"
 
 doTest
