Instead of using ftrace mechanizm in tracing, use kedr own one.

diff --git a/sources/payloads_callm/tests/caller_address/test.sh.in b/sources/payloads_callm/tests/caller_address/test.sh.in
--- a/sources/payloads_callm/tests/caller_address/test.sh.in
+++ b/sources/payloads_callm/tests/caller_address/test.sh.in
@@ -2,7 +2,7 @@
 
 control_script="sh @CMAKE_BINARY_DIR@/tools/control/kedr_test"
 
-capture_trace_script="sh @CMAKE_BINARY_DIR@/tools/capture_trace/kedr_test_capture_trace"
+capture_trace_script="@CMAKE_BINARY_DIR@/tools/capture_trace/kedr_test_capture_trace"
 
 tmpdir="@KEDR_TEST_PREFIX_TEMP_SESSION@/caller_address"
 trace_file="${tmpdir}/trace"
@@ -32,11 +32,6 @@ on_unload umount "${debugfs_mount_point}" || ! printf "Error occures while umoun
 # Clear trace collected previously
 on_load rm -f ${trace_file}
 
-on_load ${capture_trace_script} start -d "${debugfs_mount_point}" "${trace_file}" || ! printf "Cannot start capturing trace.\n"
-on_unload ${capture_trace_script} stop || ! printf "Error occures while stop capturing trace.\n"
-
-on_load ${target_module_script} load || ! printf "Cannot load target module for test.\n"
-on_unload ${target_module_script} unload || ! printf "Cannot unload target module.\n"
 eof
 
 if ! ${do_commands_script} "$commands_file" load; then
@@ -44,11 +39,21 @@ if ! ${do_commands_script} "$commands_file" load; then
 	exit 1
 fi
 
+if ! ${target_module_script} load; then
+	printf "Cannot load target module for test.\n"
+	${do_commands_script} "$commands_file" unload
+	exit 1
+fi
+
 # Do something with target_module for collect trace.
 echo 1 > /dev/cfake
 
 # Need for correct work of capture_trace_script
-sleep 0.2
+#sleep 0.2
+
+${target_module_script} unload
+
+${capture_trace_script} -s -d "${debugfs_mount_point}" -f "${trace_file}"
 
 if ! ${do_commands_script} "$commands_file" unload; then
 	printf "Error occures while finalize test.\n"
diff --git a/sources/tools/capture_trace/tests/test.sh.in b/sources/tools/capture_trace/tests/test.sh.in
--- a/sources/tools/capture_trace/tests/test.sh.in
+++ b/sources/tools/capture_trace/tests/test.sh.in
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Test standard "kedr_capture_trace" funcionality of the service, or "kedr_capture_trace_until_done".
+# Test standard "kedr_capture_trace" funcionality of the service, or "kedr_capture_trace -s".
 # Accept parameter "kedr_capture_trace" or "kedr_capture_trace_until_done"
 
 if test $# -ne 1; then
@@ -8,10 +8,16 @@ if test $# -ne 1; then
     exit 1
 fi
 
-if test $1 != 'kedr_capture_trace' && test $1 != 'kedr_capture_trace_until_done'; then
+case "$1" in
+kedr_capture_trace)
+;;
+kedr_capture_trace_until_done)
+    is_session="true"
+;;
+*)
     printf "Only 'kedr_capture_trace' or 'kedr_capture_trace_until_done' arguments are accepted\n"
     exit 1
-fi
+esac
 
 
 tmpdir="@KEDR_TEST_PREFIX_TEMP_SESSION@/capture_trace"
@@ -22,12 +28,17 @@ base_module_name=kedr_base
 base_module="@CMAKE_BINARY_DIR@/base/${base_module_name}.ko"
 controller_module_name=kedr_controller
 controller_module="@CMAKE_BINARY_DIR@/controller/${controller_module_name}.ko"
+kedr_trace_module_name=kedr_trace
+kedr_trace_module="@CMAKE_BINARY_DIR@/trace/${kedr_trace_module_name}.ko"
 payload_module_name=kedr_payload
 payload_module="@CMAKE_CURRENT_BINARY_DIR@/payload/${payload_module_name}.ko"
 target_module_name=kedr_target
 target_module="@CMAKE_CURRENT_BINARY_DIR@/target/${target_module_name}.ko"
 
-capture_trace_script="sh @CMAKE_BINARY_DIR@/tools/capture_trace/kedr_test_capture_trace"
+capture_trace_script="@CMAKE_BINARY_DIR@/tools/capture_trace/kedr_capture_trace"
+if test ${is_session}; then
+    capture_trace_script="${capture_trace_script} -s"
+fi
 
 #is_process_running pid
 is_process_running()
@@ -61,6 +72,7 @@ clean_all()
     fi
     unload_module "${controller_module_name}"
     unload_module "${payload_module_name}"
+    unload_module "${kedr_trace_module_name}"
     unload_module "${base_module_name}"
 }
 
@@ -70,6 +82,14 @@ if test $? -ne 0; then
 	printf "Failed to load KEDR base module for tests\n"
 	exit 1
 fi
+
+/sbin/insmod "${kedr_trace_module}"
+if test $? -ne 0; then
+	printf "Failed to load kedr tracing module for tests\n"
+    clean_all
+	exit 1
+fi
+
 
 /sbin/insmod "${payload_module}"
 if test $? -ne 0; then
@@ -85,8 +105,6 @@ if test $? -ne 0; then
 	exit 1
 fi
 
-# Start capturing(in the background), preliminarily enable tracepoints in the payload module and controller
-
 mkdir -p "${debugfs_mount_point}"
 mount debugfs -t debugfs "${debugfs_mount_point}"
 if test $? -ne 0; then
@@ -95,56 +113,26 @@ if test $? -ne 0; then
     exit 1
 fi
 
-echo 1 > "${debugfs_mount_point}/tracing/events/${controller_module_name}/enable"
-if test $? -ne 0; then
-    printf "Cannot enable events for controller.\n"
-    clean_all
-    exit 1
-fi
-
-echo 1 > "${debugfs_mount_point}/tracing/events/${payload_module_name}/enable"
-if test $? -ne 0; then
-    printf "Cannot enable events for payload.\n"
-    clean_all
-    exit 1
-fi
-
 capture_pid=
 
 rm -f "${trace_file}"
 
-# Start capturing trace
-case "$1" in
-kedr_capture_trace)
-    ${capture_trace_script} start -d "${debugfs_mount_point}" "${trace_file}"
-    if test $? -ne 0; then
-        printf "Failed to start capturing\n"
-        clean_all
-        exit 1
-    fi
-;;
-kedr_capture_trace_until_done)
-    ${capture_trace_script} session -d "${debugfs_mount_point}" "${trace_file}"&
-    capture_pid=$!
+# Start capturing trace(in the background)
+${capture_trace_script} -d "${debugfs_mount_point}" -f "${trace_file}"&
+capture_pid=$!
 
-    if ! is_process_running "$capture_pid"; then
-        printf "Failed to start capturing\n"
-        clean_all
-        exit 1
-    fi
-;;
-*)
-    print "Incorrect argument to test.\n"
+if ! is_process_running "$capture_pid"; then
+    printf "Failed to start capturing\n"
+    clean_all
     exit 1
-esac
-
+fi
 # Load target module
 
 /sbin/insmod "${target_module}"
 
 if test $? -ne 0; then
 	printf "Failed to load target module\n"
-    #kill $capture_pid
+    kill $capture_pid
     clean_all
 	exit 1
 fi
@@ -153,26 +141,20 @@ fi
 /sbin/rmmod "${target_module}"
 
 # Stop capturing
-case "$1" in
-kedr_capture_trace)
-    sleep 1
-    ${capture_trace_script} stop
-    if test $? -ne 0; then
-        printf "Error occures when stop capturing\n"
-        clean_all
-        exit 1
-    fi
-;;
-kedr_capture_trace_until_done)
-    wait "$capture_pid"
-;;
-esac
+if test ! ${is_session}; then
+    # Time is implementation specific for kedr tracing system(kernel part)
+    sleep 0.6
+    kill -s INT "$capture_pid"
+fi
+
+wait "$capture_pid"
 
 umount "${debugfs_mount_point}"
 
 #Unload KEDR base, payload and controller modules
 /sbin/rmmod "${controller_module}"
 /sbin/rmmod "${payload_module}"
+/sbin/rmmod "${kedr_trace_module_name}"
 /sbin/rmmod "${base_module}"
 
 #Verify trace existance
@@ -192,6 +174,5 @@ if ! grep "target_session_ends" "${trace_file}" > /dev/null; then
     printf "Ending mark wasn't captured\n"
     exit 1
 fi
-
 
 exit 0
