tests: fixed the test for caller_address: errors were ignored
Cosmetic changed have been done too.

diff --git a/sources/payloads_callm/tests/caller_address/test.sh.in b/sources/payloads_callm/tests/caller_address/test.sh.in
--- a/sources/payloads_callm/tests/caller_address/test.sh.in
+++ b/sources/payloads_callm/tests/caller_address/test.sh.in
@@ -2,7 +2,7 @@
 
 control_script="sh @CMAKE_BINARY_DIR@/tools/control/kedr_test"
 
-capture_trace_script="@CMAKE_BINARY_DIR@/tools/capture_trace/kedr_test_capture_trace"
+capture_trace_script="@CMAKE_BINARY_DIR@/tools/capture_trace/kedr_capture_trace"
 
 tmpdir="@KEDR_TEST_PREFIX_TEMP_SESSION@/caller_address"
 trace_file="${tmpdir}/trace"
@@ -40,7 +40,7 @@ if ! ${do_commands_script} "$commands_file" load; then
 fi
 
 if ! ${target_module_script} load; then
-	printf "Cannot load target module for test.\n"
+	printf "Cannot load target module for testing.\n"
 	${do_commands_script} "$commands_file" unload
 	exit 1
 fi
@@ -48,21 +48,23 @@ fi
 # Do something with target_module for collect trace.
 echo 1 > /dev/cfake0
 
-# Need for correct work of capture_trace_script
-#sleep 0.2
-
 ${target_module_script} unload
 
 ${capture_trace_script} -s -d "${debugfs_mount_point}" -f "${trace_file}"
 
 if ! ${do_commands_script} "$commands_file" unload; then
-	printf "Error occures while finalize test.\n"
+	printf "Error occurs while finalizing the test.\n"
 	exit 1
 fi
 
 # Verification of the trace
-cat "$trace_file" | grep -F "unknown+0x"
+if ! test -e "${trace_file}"; then
+    printf "Trace file does not exist: ${trace_file}\n"
+    exit 1
+fi 
+
+cat "${trace_file}" | grep -F "unknown+0x"
 if test $? -eq 0; then
-	printf "Resolving of some of the caller addresses was failed. See file '%s'.\n" "${trace_file}"
+	printf "failed to resolve some of the caller addresses. See ${trace_file}.\n"
 	exit 1
 fi
