Change a way for interception of the functions. Join kedr_base and kedr_controller into one module kedr.
Aside from standard replacement of the original function, now it is available to determine pre- and post- handlers for it.
The key advantage of these handlers - several handlers may be defined for one original function.
So, because call monitor payloads and leak checker only observe target module, they make use such handlers and do not conflict with each other and with fault simulation payloads.

Decouple call monitor and fault simulation payloads.

diff --git a/sources/tests/payload_api/in_init/test.sh.in b/sources/tests/payload_api/in_init/test.sh.in
--- a/sources/tests/payload_api/in_init/test.sh.in
+++ b/sources/tests/payload_api/in_init/test.sh.in
@@ -18,13 +18,8 @@
 ########################################################################
 checkPrereqs()
 {
-    if test ! -f "${BASE_MODULE}"; then
-        printf "Base module is missing: ${BASE_MODULE}\n"
-        exit 1
-    fi
-    
-    if test ! -f "${CONTROLLER_MODULE}"; then
-        printf "Controller module is missing: ${CONTROLLER_MODULE}\n"
+    if test ! -f "${KEDR_MODULE}"; then
+        printf "KEDR core module is missing: ${KEDR_MODULE}\n"
         exit 1
     fi
     
@@ -53,19 +48,14 @@ cleanupAll()
         cd "${WORK_DIR}"
     fi
     
-    lsmod | grep "@CONTROLLER_NAME@" > /dev/null 2>&1
-    if test $? -eq 0; then
-        /sbin/rmmod "@CONTROLLER_NAME@"
-    fi
-    
     lsmod | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
         /sbin/rmmod "${PAYLOAD_NAME}"
     fi
     
-    lsmod | grep "@BASE_NAME@" > /dev/null 2>&1
+    lsmod | grep "@KEDR_NAME@" > /dev/null 2>&1
     if test $? -eq 0; then
-        /sbin/rmmod "@BASE_NAME@"
+        /sbin/rmmod "@KEDR_NAME@"
     fi
 }
 
@@ -74,7 +64,7 @@ cleanupAll()
 ########################################################################
 doTest()
 {
-    /sbin/insmod "${BASE_MODULE}" || exit 1
+    /sbin/insmod "${KEDR_MODULE}" target_name="${TARGET_NAME}" || exit 1
 
     /sbin/insmod "${PAYLOAD_MODULE}"
     if test $? -ne 0; then
@@ -86,13 +76,6 @@ doTest()
     OUT_PARAM_FILE="/sys/module/${PAYLOAD_NAME}/parameters/target_in_init"
     if test ! -e "${OUT_PARAM_FILE}"; then
         printf "Parameter file does not exist: ${OUT_PARAM_FILE}\n"
-        cleanupAll
-        exit 1
-    fi
-
-    /sbin/insmod "${CONTROLLER_MODULE}" target_name="${TARGET_NAME}"
-    if test $? -ne 0; then
-        printf "Failed to load the controller\n"
         cleanupAll
         exit 1
     fi
@@ -121,14 +104,7 @@ doTest()
         exit 1
     fi
 
-    /sbin/rmmod "@CONTROLLER_NAME@"
-    if test $? -ne 0; then
-        printf "Failed to unload the controller module\n"
-        cleanupAll
-        exit 1
-    fi
-
-    /sbin/rmmod "@BASE_NAME@" || exit 1
+    /sbin/rmmod "@KEDR_NAME@" || exit 1
     
     # Check the saved result
     printf "Expected value of target_in_init flag is '${IN_INIT}', "
@@ -152,8 +128,7 @@ IN_INIT=$1
 IN_ATOMIC=$2
 printf "Mode: in_init=${IN_INIT}, in_atomic=${IN_ATOMIC}\n"
 
-BASE_MODULE="@BASE_DIR@/@BASE_NAME@.ko"
-CONTROLLER_MODULE="@CONTROLLER_DIR@/@CONTROLLER_NAME@.ko"
+KEDR_MODULE="@KEDR_DIR@/@KEDR_NAME@.ko"
 
 TARGET_NAME="test_in_init_target"
 TARGET_MODULE="target/${TARGET_NAME}.ko"
@@ -163,8 +138,7 @@ PAYLOAD_MODULE="payload/${PAYLOAD_NAME}.ko"
 
 checkPrereqs
 
-printf "Base module: ${BASE_MODULE}\n"
-printf "Controller module: ${CONTROLLER_MODULE}\n"
+printf "Kedr core module: ${KEDR_MODULE}\n"
 printf "Target module: ${TARGET_MODULE}\n"
 printf "Payload module: ${PAYLOAD_MODULE}\n"
 
diff --git a/sources/tests/payload_api/notifications/test.sh.in b/sources/tests/payload_api/notifications/test.sh.in
--- a/sources/tests/payload_api/notifications/test.sh.in
+++ b/sources/tests/payload_api/notifications/test.sh.in
@@ -20,13 +20,8 @@
 ########################################################################
 checkPrereqs()
 {
-    if test ! -f "${BASE_MODULE}"; then
-        printf "Base module is missing: ${BASE_MODULE}\n"
-        exit 1
-    fi
-    
-    if test ! -f "${CONTROLLER_MODULE}"; then
-        printf "Controller module is missing: ${CONTROLLER_MODULE}\n"
+    if test ! -f "${KEDR_MODULE}"; then
+        printf "KEDR core module is missing: ${KEDR_MODULE}\n"
         exit 1
     fi
     
@@ -53,19 +48,14 @@ cleanupAll()
         /sbin/rmmod "${TARGET_NAME}"
     fi
     
-    lsmod | grep "@CONTROLLER_NAME@" > /dev/null 2>&1
-    if test $? -eq 0; then
-        /sbin/rmmod "@CONTROLLER_NAME@"
-    fi
-    
     lsmod | grep "${PAYLOAD_NAME}" > /dev/null 2>&1
     if test $? -eq 0; then
         /sbin/rmmod "${PAYLOAD_NAME}"
     fi
     
-    lsmod | grep "@BASE_NAME@" > /dev/null 2>&1
+    lsmod | grep "@KEDR_NAME@" > /dev/null 2>&1
     if test $? -eq 0; then
-        /sbin/rmmod "@BASE_NAME@"
+        /sbin/rmmod "@KEDR_NAME@"
     fi
 }
 
@@ -108,7 +98,7 @@ checkOutputStrings()
 ########################################################################
 doTest()
 {
-    /sbin/insmod "${BASE_MODULE}" || exit 1
+    /sbin/insmod "${KEDR_MODULE}" target_name="${TARGET_NAME}" || exit 1
 
     /sbin/insmod "${PAYLOAD_MODULE}" \
         set_load_fn=${SET_LOAD_FN} \
@@ -148,13 +138,6 @@ doTest()
     OUT_UNLOAD_PARAM="/sys/module/${PAYLOAD_NAME}/parameters/target_unload_name"
     if test ! -e "${OUT_UNLOAD_PARAM}"; then
         printf "Parameter file does not exist: ${OUT_UNLOAD_PARAM}\n"
-        cleanupAll
-        exit 1
-    fi
-
-    /sbin/insmod "${CONTROLLER_MODULE}" target_name="${TARGET_NAME}"
-    if test $? -ne 0; then
-        printf "Failed to load the controller\n"
         cleanupAll
         exit 1
     fi
@@ -212,8 +195,7 @@ SET_LOAD_FN=$2
 SET_UNLOAD_FN=$3
 printf "Mode: set_load_fn=${SET_LOAD_FN}, set_unload_fn=${SET_UNLOAD_FN}\n"
 
-BASE_MODULE="@BASE_DIR@/@BASE_NAME@.ko"
-CONTROLLER_MODULE="@CONTROLLER_DIR@/@CONTROLLER_NAME@.ko"
+KEDR_MODULE="@KEDR_DIR@/@KEDR_NAME@.ko"
 
 TARGET_NAME="test_${TARGET_DIR}"
 TARGET_MODULE="${TARGET_DIR}/${TARGET_NAME}.ko"
diff --git a/sources/tests/payload_api/register/test.sh.in b/sources/tests/payload_api/register/test.sh.in
--- a/sources/tests/payload_api/register/test.sh.in
+++ b/sources/tests/payload_api/register/test.sh.in
@@ -28,8 +28,8 @@
 ########################################################################
 checkPrereqs()
 {
-    if test ! -f "${BASE_MODULE}"; then
-        printf "Base module is missing: ${BASE_MODULE}\n"
+    if test ! -f "${KEDR_MODULE}"; then
+        printf "KEDR core module is missing: ${KEDR_MODULE}\n"
         exit 1
     fi
     
@@ -51,9 +51,9 @@ cleanupAll()
         /sbin/rmmod "${PAYLOAD_NAME}"
     fi
     
-    lsmod | grep "@BASE_NAME@" > /dev/null 2>&1
+    lsmod | grep "@KEDR_NAME@" > /dev/null 2>&1
     if test $? -eq 0; then
-        /sbin/rmmod "@BASE_NAME@"
+        /sbin/rmmod "@KEDR_NAME@"
     fi
 }
 
@@ -62,7 +62,7 @@ cleanupAll()
 ########################################################################
 doTest()
 {
-    /sbin/insmod "${BASE_MODULE}" || exit 1
+    /sbin/insmod "${KEDR_MODULE}" || exit 1
 
     /sbin/insmod "${PAYLOAD_MODULE}" scenario_number=${SCEN_NO}
     if test $? -ne 0; then
@@ -88,7 +88,7 @@ doTest()
         exit 1
     fi
 
-    /sbin/rmmod "@BASE_NAME@" || exit 1
+    /sbin/rmmod "@KEDR_NAME@" || exit 1
     
     # Check the saved result
     printf "Test result (1 - passed, other value - failed): ${TEST_PASSED}\n"
@@ -110,14 +110,14 @@ fi
 SCEN_NO=$1
 printf "Scenario number is ${SCEN_NO}\n"
 
-BASE_MODULE="@BASE_DIR@/@BASE_NAME@.ko"
+KEDR_MODULE="@KEDR_DIR@/@KEDR_NAME@.ko"
 
 PAYLOAD_NAME="test_reg_payload"
 PAYLOAD_MODULE="payload/${PAYLOAD_NAME}.ko"
 
 checkPrereqs
 
-printf "Base module: ${BASE_MODULE}\n"
+printf "Kedr core module: ${KEDR_MODULE}\n"
 printf "Payload module: ${PAYLOAD_MODULE}\n"
 
 doTest
