sources/CMakeLists.txt: Fix unquoted usage of '\n'. Modern cmake warns about that. sources/tools/control/kedr.in: Fix incorrect variable reference ${$OPTIND}, which caused bash error(in error path). Also improve error-reporting: Use 'kedr:' prefix for logic errors(like incorrect options). Use 'Error:' prefix for runtime errors(like "cannot read file"). Print usage only when 'kedr' tool is run without arguments.

diff --git a/sources/tools/control/kedr.in b/sources/tools/control/kedr.in
--- a/sources/tools/control/kedr.in
+++ b/sources/tools/control/kedr.in
@@ -28,24 +28,24 @@ newline='
 
 usage()
 {
-	printf "Usage: \n"
-	printf "\tkedr start <target_module_name> [ -c <conf_string> | -f <conf_file> ...]\n"
-	printf "\t\tLoad KEDR components to operate on the target module.\n"
-	printf "\tkedr stop\n"
-	printf "\t\tUnload KEDR components.\n"
-	printf "\tkedr restart\n"
-	printf "\t\tUnload KEDR components and load it with the same configuration.\n"
-	printf "\tkedr status\n"
-	printf "\t\tDisplay status of KEDR.\n"
-	printf "\tkedr --help\n"
-	printf "\t\tDisplay this help and exit.\n"
-	printf "\tkedr --version\n"
-	printf "\t\tDisplay version information and exit.\n"
+    printf "Usage: \n"
+    printf "\tkedr start <target_module_name> [ -c <conf_string> | -f <conf_file> ...]\n"
+    printf "\t\tLoad KEDR components to operate on the target module.\n"
+    printf "\tkedr stop\n"
+    printf "\t\tUnload KEDR components.\n"
+    printf "\tkedr restart\n"
+    printf "\t\tUnload KEDR components and load it with the same configuration.\n"
+    printf "\tkedr status\n"
+    printf "\t\tDisplay status of KEDR.\n"
+    printf "\tkedr --help\n"
+    printf "\t\tDisplay this help and exit.\n"
+    printf "\tkedr --version\n"
+    printf "\t\tDisplay version information and exit.\n"
 }
 
 version()
 {
-	printf "KEDR version @KEDR_VERSION@.\n"
+    printf "KEDR version @KEDR_VERSION@.\n"
 }
 
 # default config directory and file
@@ -60,7 +60,7 @@ RMMOD=rmmod
 RMMOD_ONLY_ONE=rmmod_only_one
 rmmod_only_one()
 {
-	${RMMOD} "$1"
+    ${RMMOD} "$1"
 }
 
 # directory for temporary files
@@ -71,8 +71,7 @@ start_conf_file=${tmp_dir}/start.conf
 
 
 if test $# -eq 0; then
-    printf "kedr: command should be specified\n"
-	usage
+    usage
     exit 1
 fi
 
@@ -151,7 +150,7 @@ parse_conf_on_load()
             -e ":on_load; b out; :on_unload; d" \
             -e ":error; s/^/printf \"%s\\\\n\" \"Incorrect config line '/; s/$/'\"/; p; d;" \
             -e ":out; i\line=\\\\" -e" =;" -e "s/^\(.\{0,\}\)$/cat << \"EOF\"\n\\1\nEOF\n\\1/; p;" \
-			-e "a result=\$?\nif test \$result -ne 0; then echo \$line > \$1; exit \$result; fi\n" "$1"
+            -e "a result=\$?\nif test \$result -ne 0; then echo \$line > \$1; exit \$result; fi\n" "$1"
 }
 
 # parse_conf_on_unload conf_file [line_number]
@@ -162,7 +161,7 @@ parse_conf_on_load()
 parse_conf_on_unload()
 {
     { if test $2; then head -n $(($2 - 1)) "$1"; else cat "$1"; fi; } | sed '1!G;h;$!d' | \
-	sed -n  -e "${regex_parse_conf}" -e ":module; :payload; ${regex_up_to_space}; ${regex_is_alias};" \
+    sed -n  -e "${regex_parse_conf}" -e ":module; :payload; ${regex_up_to_space}; ${regex_is_alias};" \
             -e ":alias; s!^!${MODPROBE} -r !; b out; :notalias; s!^!${RMMOD} !; b out;" \
             -e ":on_unload; b out; :on_load; d" \
             -e ":error; s/^/printf \"%s\\\\n\" \"Incorrect config line '/; s/$/'\"/; p; d;" \
@@ -205,15 +204,15 @@ execute_conf_on_load()
 {
     # Output parsing results into file for debugging purposes.
     if ! parse_conf_on_load "$1" > ${tmp_dir}/commands_tmp.txt; then
-		printf "Failed to parse configuration file.\n"        
-		return 1
-	fi
+        printf "Error: Failed to parse configuration file.\n"        
+        return 1
+    fi
     if ! sh ${tmp_dir}/commands_tmp.txt "${tmp_dir}/line.txt"; then
-		printf "Failed to execute commands to start KEDR... performing rollback.\n"        
-		line_number=`cat "${tmp_dir}/line.txt"`
+        printf "Error: Failed to execute commands to start KEDR. Performing rollback.\n"        
+        line_number=`cat "${tmp_dir}/line.txt"`
         rollback "${start_conf_file}" "$line_number"
         return 1
-	fi
+    fi
 }
 
 # execute_conf_on_unload conf_file
@@ -221,22 +220,22 @@ execute_conf_on_load()
 # Execute lines in the configuration file in 'on_unload' mode.
 execute_conf_on_unload()
 {
-	if ! parse_conf_on_unload "$1" > ${tmp_dir}/commands_unload_tmp.txt; then
-		printf "Failed to parse configuration file.\n"        
-		return 1
-	fi
-	sh ${tmp_dir}/commands_unload_tmp.txt
+    if ! parse_conf_on_unload "$1" > ${tmp_dir}/commands_unload_tmp.txt; then
+        printf "Error: Failed to parse configuration file.\n"
+        return 1
+    fi
+    sh ${tmp_dir}/commands_unload_tmp.txt
 }
 # rollback conf_file string_number
 #
 # Rollback first 'string_number' commands from the config files(performs unload operation for them)
 rollback()
 {
-	if ! parse_conf_on_unload "$1" "$2"> ${tmp_dir}/commands_rollback_tmp.txt; then
-		printf "Failed to parse configuration file.\n"        
-		return 1
-	fi
-	sh ${tmp_dir}/commands_rollback_tmp.txt
+    if ! parse_conf_on_unload "$1" "$2"> ${tmp_dir}/commands_rollback_tmp.txt; then
+        printf "Error: Failed to parse configuration file.\n"
+        return 1
+    fi
+    sh ${tmp_dir}/commands_rollback_tmp.txt
 }
 
 
@@ -260,60 +259,63 @@ fi
 case ${command} in
 start)
     if is_module_running ${kedr_name}; then
-        printf "%s\n" "Service is already running. To stop it, execute '$0 stop'"
+        printf "kedr: Service is already running. To stop it, execute '$0 stop'.\n"
         exit 1
     fi
     if test $# -eq 0; then
-        printf "Name of the target module should be specified as the second argument\n"
+        printf "kedr: Name of the target module should be specified for 'start' command.\n"
         exit 1
     fi
     target_name=`get_module_name "$1"`
     shift
     if is_module_running ${target_name}; then
-        printf "KEDR can not start because the target module is already loaded. Please unload the target module first.\n"
+        printf "kedr: Service cannot be started because the target module is already loaded. Please unload the target module first.\n"
         exit 1
     fi
-    printf "Starting KEDR...\n"
     #collect all parts of the configuration to the ${start_conf_file}
     mkdir -p ${tmp_dir} || (printf "Cannot create directory for temporary files\n" && exit 1)
-	# Create config file for processing
+    # Create config file for processing
     #Add loading of kedr module to the config file
     printf "module %s target_name=%s\n" "@KEDR_FILE@" "$target_name"> "${start_conf_file}"
     if test $? -ne 0; then
-        printf "Cannot write to temporary file\n"
+        printf "Error: Cannot write to temporary file.\n"
         exit 1
     fi
     #Append config file content formed from options to the config file
     while getopts ":c:f:" opt; do
-		case $opt in
-		c)
-			non_default_config=1
-			printf "%s\n" "$OPTARG" >> "${start_conf_file}"
-		;;
-		f)
-			non_default_config=1
-			if test -e "$OPTARG"; then
+        case $opt in
+        c)
+            non_default_config=1
+            printf "%s\n" "$OPTARG" >> "${start_conf_file}"
+        ;;
+        f)
+            non_default_config=1
+            if test -e "$OPTARG"; then
                 conf_file="$OPTARG"
             else
                 if test -e "${default_config_dir}/$OPTARG"; then
                     conf_file="${default_config_dir}/$OPTARG"
                 else
-                    printf "Configuration file '%s' does not exist.\n" "$OPTARG"
+                    printf "Error: Configuration file '%s' does not exist.\n" "$OPTARG"
                     exit 1
                 fi
             fi
-			cat "${conf_file}" >> "${start_conf_file}"
-			printf "\n" >> "${start_conf_file}"
-		;;
-		?)
-			usage
-			exit 1
-		;;
-		esac
-	done
-    if test "$OPTIND" -lt "$#"; then
-        print "Unknown parameter %s\n" "${$OPTIND}"
-        usage
+            cat "${conf_file}" >> "${start_conf_file}"
+            printf "\n" >> "${start_conf_file}"
+        ;;
+        \?)
+	    printf "kedr: Invalid option -$OPTARG for 'start' command.\n"
+            exit 1
+	;;
+	:)
+	    printf "kedr: Option -$OPTARG for 'start' command requires argument.\n"
+            exit 1
+        ;;
+        esac
+    done
+    shift $(($OPTIND-1))
+    if test $# -ne 0; then
+	printf "kedr: Unexpected parameter '%s' for 'start' command.\n" "$1"
         exit 1
     fi
     #Or use default config file content
@@ -322,9 +324,9 @@ start)
         printf "\n" >> "${start_conf_file}"
     fi
 
+    printf "Starting KEDR...\n"
     execute_conf_on_load "${start_conf_file}"
     if test $? -ne 0; then
-        # In the release version next line should be uncommented
         rm -f "${start_conf_file}"
         exit 1
     fi
@@ -332,23 +334,23 @@ start)
     ;;
 stop)
     if ! is_module_running ${kedr_name}; then
-        printf "Service is not running. To start it, execute '%s start'\n" "$0"
+        printf "kedr: Service is not running. To start it, execute '$0 start <target_name>'.\n"
         exit 1
     fi
     target_name=`cat /sys/module/${kedr_name}/parameters/target_name`
     if is_module_running ${target_name}; then
-        printf "KEDR cannot be stopped because the target module is still loaded. Please unload the target module first.\n"
+        printf "kedr: Service cannot be stopped because the target module is still loaded. Please unload the target module first.\n"
         exit 1
     fi
     printf "Stopping KEDR...\n"
     execute_conf_on_unload "${start_conf_file}";
-	if is_module_running ${kedr_name}; then
-    	printf "Failed to unload KEDR.\n"
-		printf "Please fix errors occured while unloading and retry.\n"
-		exit 1
-	fi
-	rm -f "${start_conf_file}"
-	printf "KEDR stopped.\n"
+    if is_module_running ${kedr_name}; then
+        printf "Error: Failed to unload KEDR.\n"
+        printf "Please fix errors occured while unloading and retry.\n"
+        exit 1
+    fi
+    rm -f "${start_conf_file}"
+    printf "KEDR stopped.\n"
     ;;
 status)
     if is_module_running ${kedr_name}; then
@@ -371,36 +373,36 @@ status)
     ;;
 restart)
     if ! is_module_running ${kedr_name}; then
-        printf "%s\n" "Service is not running. To start it, execute '$0 start'"
+        printf "kedr: Service is not running. To start it, execute '$0 start <target_name>'.\n"
         exit 1
     fi
     target_name=`cat /sys/module/${kedr_name}/parameters/target_name`
     if is_module_running ${target_name}; then
-        printf "KEDR cannot be stopped because the target module is still loaded. Please unload the target module first.\n"
+        printf "kedr: Service cannot be restarted because the target module is still loaded. Please unload the target module first.\n"
         exit 1
     fi
     printf "Stopping KEDR...\n"
     execute_conf_on_unload "${start_conf_file}"
     if is_module_running "${kedr_name}"; then
-        printf "Failed to stop KEDR\n"
+        printf "Error: Failed to stop KEDR.\n"
         exit 1
     fi
     printf "Starting KEDR...\n"
     execute_conf_on_load "${start_conf_file}"
     if test $? -ne 0; then
-        printf "Failed to start KEDR again.\n"
+        printf "Error: Failed to start KEDR again.\n"
         rm -f "${start_conf_file}"
         exit 1
     fi
     printf "KEDR started.\n"
     ;;
 --help)
-	printf "KEDR service.\n"
-	usage
-	;;
+    printf "KEDR service.\n"
+    usage
+    ;;
 --version)
-	version
-	;;
+    version
+    ;;
 *)
-    printf "%s\n" "kedr: Incorrect command '$command', should be 'start', 'stop', 'restart' or 'status'."
+    printf "kedr: Incorrect command '$command'. Should be 'start', 'stop', 'restart' or 'status'.\n"
 esac
