Change test for instrumentor component of the KEDR core, so instrumentation is performed in the module notifier instead of init function of the instrumented module.
This change is done because on some systems memory pages, which contain module code, are made readonly just after module notifier calls.
So, instrumentation in the module init function caused page fault on such systems.

diff --git a/sources/core/tests/components/instrumentor/test.sh.in b/sources/core/tests/components/instrumentor/test.sh.in
--- a/sources/core/tests/components/instrumentor/test.sh.in
+++ b/sources/core/tests/components/instrumentor/test.sh.in
@@ -7,13 +7,13 @@ test_module="@CMAKE_CURRENT_BINARY_DIR@/test_module/${test_module_name}.ko"
 
 test_value_file="/sys/module/${instrumentor_module_name}/parameters/test_value"
 
-if ! insmod "${instrumentor_module}"; then
-    printf "Failed to insert instrumentor module.\n"
+if ! insmod "${instrumentor_module}" "target_name=${test_module_name}"; then
+    printf "Failed to insert instrumentor module into kernel.\n"
     exit 1
 fi
 
 if ! insmod "${test_module}"; then
-    printf "Failed to insert test module.\n"
+    printf "Failed to insert test module into kernel.\n"
     rmmod "${instrumentor_module}"
     exit 1
 fi
